[package]
name = "egui-video"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "a video library for egui"
repository = "https://github.com/n00kii/egui-video"
readme = "README.md"
authors = ["n00kii"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
from_bytes = ["dep:tempfile"]

[dependencies]
egui = "0.20.1"
ffmpeg-next = { git = "https://github.com/n00kii/rust-ffmpeg.git" }
anyhow = "1.0.66"
timer = "0.2.0"
chrono = "0.4.22"
tempfile = {version = "3.3.0", optional = true}
sdl2 = { version = "0.35.2", features = ["bundled"]}
ringbuf = "0.3.1"
parking_lot = "0.12.1"
itertools = "0.10.5"

[dev-dependencies]
rfd = "0.10.0"
eframe = "0.20.1"